In [2]:
#Importamos librerias
import pandas as pd

In [2]:
#Importamos dataset de negocios de yelp
yelp_restaurants = pd.read_pickle('restaurants_yelp.pkl')
yelp_restaurants.head()

,index,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,CA,19107,39.955505,-75.155564,4.0,80,1,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...","Restaurants, Food, Bubble Tea, Coffee & Tea, B...","{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ..."
1,5,CF33F8-E6oudUQ46HnavjQ,Sonic Drive-In,615 S Main St,Ashland City,AZ,37015,36.269593,-87.058943,2.0,6,1,"{'BusinessParking': 'None', 'BusinessAcceptsCr...","Burgers, Fast Food, Sandwiches, Food, Ice Crea...","{'Monday': '0:0-0:0', 'Tuesday': '6:0-22:0', '..."
2,8,k0hlBqXX-Bt0vf1op7Jr1w,Tsevi's Pub And Grill,8025 Mackenzie Rd,Affton,TN,63123,38.565165,-90.321087,3.0,19,0,"{'Caters': 'True', 'Alcohol': 'u'full_bar'', '...","Pubs, Restaurants, Italian, Bars, American (Tr...",None
3,9,bBDDEgkFA1Otx9Lfe7BZUQ,Sonic Drive-In,2312 Dickerson Pike,Nashville,MO,37207,36.208102,-86.76817,1.5,10,1,"{'RestaurantsAttire': ''casual'', 'Restaurants...","Ice Cream & Frozen Yogurt, Fast Food, Burgers,...","{'Monday': '0:0-0:0', 'Tuesday': '6:0-21:0', '..."
4,11,eEOYSgkmpB90uNA7lDOMRA,Vietnamese Food Truck,,Tampa Bay,MO,33602,27.955269,-82.45632,4.0,10,1,"{'Alcohol': ''none'', 'OutdoorSeating': 'None'...","Vietnamese, Food, Restaurants, Food Trucks","{'Monday': '11:0-14:0', 'Tuesday': '11:0-14:0'..."

In [3]:
#Observamos mas de cerca
yelp_restaurants.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 52286 entries, 0 to 52285
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   index         52286 non-null  int64
 1   business_id   52286 non-null  object
 2   name          52286 non-null  object
 3   address       52286 non-null  object
 4   city          52286 non-null  object
 5   state         52286 non-null  object
 6   postal_code   52286 non-null  object
 7   latitude      52286 non-null  object
 8   longitude     52286 non-null  object
 9   stars         52286 non-null  object
 10  review_count  52286 non-null  object
 11  is_open       52286 non-null  object
 12  attributes    51720 non-null  object
 13  categories    52286 non-null  object
 14  hours         45007 non-null  object
dtypes: int64(1), object(14)
memory usage: 6.4+ MB

Este caso parece ser relativamente más sencillo. Prácticamente no hay valores nulos. Simplemente hay que descartar columnas, renombrar y reordenar.

In [4]:
yelp_restaurants.drop(columns=['index','address','stars','review_count','is_open','hours'],inplace=True)
yelp_restaurants.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 52286 entries, 0 to 52285
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   business_id  52286 non-null  object
 1   name         52286 non-null  object
 2   city         52286 non-null  object
 3   state        52286 non-null  object
 4   postal_code  52286 non-null  object
 5   latitude     52286 non-null  object
 6   longitude    52286 non-null  object
 7   attributes   51720 non-null  object
 8   categories   52286 non-null  object
dtypes: object(9)
memory usage: 4.0+ MB

In [6]:
#Renombramos
yelp_restaurants.rename(columns={'business_id':'Id_Restaurant','name':'Nombre','city':'Ciudad','state':'Estado','postal_code':'Cod_postal',
                                 'latitude':'Latitud','longitude':'Longitud','attributes':'Atributos','categories':'Tipo'},inplace=True)
yelp_restaurants.head()

,Id_Restaurant,Nombre,Ciudad,Estado,Cod_postal,Latitud,Longitud,Atributos,Tipo
0,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,Philadelphia,CA,19107,39.955505,-75.155564,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...","Restaurants, Food, Bubble Tea, Coffee & Tea, B..."
1,CF33F8-E6oudUQ46HnavjQ,Sonic Drive-In,Ashland City,AZ,37015,36.269593,-87.058943,"{'BusinessParking': 'None', 'BusinessAcceptsCr...","Burgers, Fast Food, Sandwiches, Food, Ice Crea..."
2,k0hlBqXX-Bt0vf1op7Jr1w,Tsevi's Pub And Grill,Affton,TN,63123,38.565165,-90.321087,"{'Caters': 'True', 'Alcohol': 'u'full_bar'', '...","Pubs, Restaurants, Italian, Bars, American (Tr..."
3,bBDDEgkFA1Otx9Lfe7BZUQ,Sonic Drive-In,Nashville,MO,37207,36.208102,-86.76817,"{'RestaurantsAttire': ''casual'', 'Restaurants...","Ice Cream & Frozen Yogurt, Fast Food, Burgers,..."
4,eEOYSgkmpB90uNA7lDOMRA,Vietnamese Food Truck,Tampa Bay,MO,33602,27.955269,-82.45632,"{'Alcohol': ''none'', 'OutdoorSeating': 'None'...","Vietnamese, Food, Restaurants, Food Trucks"

In [8]:
#Reordenamos
yelp_restaurants = yelp_restaurants[['Id_Restaurant', 'Nombre', 'Ciudad', 'Estado', 'Cod_postal', 'Latitud',
                                    'Longitud','Tipo','Atributos']]
yelp_restaurants.head()

,Id_Restaurant,Nombre,Ciudad,Estado,Cod_postal,Latitud,Longitud,Tipo,Atributos
0,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,Philadelphia,CA,19107,39.955505,-75.155564,"Restaurants, Food, Bubble Tea, Coffee & Tea, B...","{'RestaurantsDelivery': 'False', 'OutdoorSeati..."
1,CF33F8-E6oudUQ46HnavjQ,Sonic Drive-In,Ashland City,AZ,37015,36.269593,-87.058943,"Burgers, Fast Food, Sandwiches, Food, Ice Crea...","{'BusinessParking': 'None', 'BusinessAcceptsCr..."
2,k0hlBqXX-Bt0vf1op7Jr1w,Tsevi's Pub And Grill,Affton,TN,63123,38.565165,-90.321087,"Pubs, Restaurants, Italian, Bars, American (Tr...","{'Caters': 'True', 'Alcohol': 'u'full_bar'', '..."
3,bBDDEgkFA1Otx9Lfe7BZUQ,Sonic Drive-In,Nashville,MO,37207,36.208102,-86.76817,"Ice Cream & Frozen Yogurt, Fast Food, Burgers,...","{'RestaurantsAttire': ''casual'', 'Restaurants..."
4,eEOYSgkmpB90uNA7lDOMRA,Vietnamese Food Truck,Tampa Bay,MO,33602,27.955269,-82.45632,"Vietnamese, Food, Restaurants, Food Trucks","{'Alcohol': ''none'', 'OutdoorSeating': 'None'..."

In [4]:
yelp_restaurants.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 52286 entries, 0 to 52285
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id_Restaurant  52286 non-null  object
 1   Nombre         52286 non-null  object
 2   Ciudad         52286 non-null  object
 3   Estado         52286 non-null  object
 4   Cod_postal     52286 non-null  object
 5   Latitud        52286 non-null  object
 6   Longitud       52286 non-null  object
 7   Tipo           52286 non-null  object
 8   Atributos      51720 non-null  object
dtypes: object(9)
memory usage: 4.0+ MB

In [5]:
#Vamos a observar si hay negocios que se encuentren duplicados.
#Es decir que tengan distinto Id (ya se descartó antes los de igual Id) pero coincidan nombre y ubicación.
duplicados_yelp = yelp_restaurants[yelp_restaurants.duplicated(subset=['Nombre','Cod_postal'],keep=False)].sort_values(by='Nombre')
duplicados_yelp.head()

,Id_Restaurant,Nombre,Ciudad,Estado,Cod_postal,Latitud,Longitud,Tipo,Atributos
10864,x67huqR9qbjoodRBu3KWfg,1st NE International Market,Philadelphia,MO,19149,40.041595,-75.055165,"Cantonese, Grocery, Food, Chinese, Restaurants...","{'BikeParking': 'False', 'GoodForMeal': '{'des..."
3615,jOhRFAJYBHU3chGwg1e4_A,1st NE International Market,Philadelphia,TN,19149,40.041594,-75.054799,"Food, Grocery, Restaurants, International Groc...","{'RestaurantsDelivery': 'False', 'RestaurantsP..."
25539,CyKEqW5UjhPB2pMEPrUsYg,A King's Cafe,Philadelphia,NV,19141,40.04756,-75.150719,"Cafes, Restaurants","{'BusinessParking': '{'garage': False, 'street..."
17723,RGjzDIO6HlOU3Uo4IqVAww,A King's Cafe,Philadelphia,LA,19141,40.047863,-75.14398,"Chicken Wings, Restaurants, Seafood, Breakfast...","{'RestaurantsTakeOut': 'True', 'RestaurantsDel..."
33920,-HMqisHgmwr4k8zwT3tp5Q,Amber Indian Restaurant,Indianapolis,MO,46250,39.904832,-86.065988,"Restaurants, Desserts, Indian, Food, Pakistani","{'HasTV': 'True', 'Alcohol': 'u'beer_and_wine'..."

In [6]:
#Vemos que hay y tienen la misma ubicación. Vemos cuantos son.
duplicados_yelp.reset_index(inplace=True)
duplicados_yelp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2613 entries, 0 to 2612
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   index          2613 non-null   int64
 1   Id_Restaurant  2613 non-null   object
 2   Nombre         2613 non-null   object
 3   Ciudad         2613 non-null   object
 4   Estado         2613 non-null   object
 5   Cod_postal     2613 non-null   object
 6   Latitud        2613 non-null   object
 7   Longitud       2613 non-null   object
 8   Tipo           2613 non-null   object
 9   Atributos      2596 non-null   object
dtypes: int64(1), object(9)
memory usage: 204.3+ KB

Es un numero impar. Es decir que hay algunos que están repetidos mas de 1 vez.

In [7]:
#Vemos cuantos negocios son
negocios_duplicados_yelp = duplicados_yelp.drop_duplicates(subset=['Nombre','Cod_postal'])
negocios_duplicados_yelp.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1194 entries, 0 to 2611
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   index          1194 non-null   int64
 1   Id_Restaurant  1194 non-null   object
 2   Nombre         1194 non-null   object
 3   Ciudad         1194 non-null   object
 4   Estado         1194 non-null   object
 5   Cod_postal     1194 non-null   object
 6   Latitud        1194 non-null   object
 7   Longitud       1194 non-null   object
 8   Tipo           1194 non-null   object
 9   Atributos      1187 non-null   object
dtypes: int64(1), object(9)
memory usage: 102.6+ KB

Vamos a quedarnos con uno de los duplicados y descartar los otros. Sin embargo, vamos a cambiar primero el id de las reseñas así no perdemos información.

In [8]:
#Tomamos los ids a conservar y los que se van a cambiar
lista_duplicados = []
for n in negocios_duplicados_yelp['Id_Restaurant'].values:
    aux = []
    nombre = negocios_duplicados_yelp[negocios_duplicados_yelp['Id_Restaurant']==n]['Nombre'].values[0]
    cod_postal = negocios_duplicados_yelp[negocios_duplicados_yelp['Id_Restaurant']==n]['Cod_postal'].values[0]
    for d in range(duplicados_yelp.shape[0]):
        if (duplicados_yelp['Nombre'][d] == nombre) and (duplicados_yelp['Cod_postal'][d] == cod_postal) and (duplicados_yelp['Id_Restaurant'][d] != n):
            aux.append(duplicados_yelp['Id_Restaurant'][d])
    lista_duplicados.append([n,aux])

In [9]:
#Armammos dataframe
duplicados_yelp_df = pd.DataFrame(data=lista_duplicados,columns=['Conservar','Cambiar'])
duplicados_yelp_df.head()

                Conservar                   Cambiar
0  x67huqR9qbjoodRBu3KWfg  [jOhRFAJYBHU3chGwg1e4_A]
1  CyKEqW5UjhPB2pMEPrUsYg  [RGjzDIO6HlOU3Uo4IqVAww]
2  -HMqisHgmwr4k8zwT3tp5Q  [_ElX5QsAd-CXxlW0vt8Ftw]
3  HWnfpi2vXDTNGTCSFd97PQ  [mzAFaxDgKEVhINViBlyWvA]
4  DcRfabRzYkddMEUFyPMBgw  [XkZwD46WcsAlbpg1inwbLQ]

In [10]:
#Descartamos los duplicados
yelp_restaurants.drop_duplicates(subset=['Nombre','Cod_postal'],inplace=True)
yelp_restaurants.reset_index(inplace=True)
yelp_restaurants.drop(columns='index',inplace=True)
yelp_restaurants.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50867 entries, 0 to 50866
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id_Restaurant  50867 non-null  object
 1   Nombre         50867 non-null  object
 2   Ciudad         50867 non-null  object
 3   Estado         50867 non-null  object
 4   Cod_postal     50867 non-null  object
 5   Latitud        50867 non-null  object
 6   Longitud       50867 non-null  object
 7   Tipo           50867 non-null  object
 8   Atributos      50310 non-null  object
dtypes: object(9)
memory usage: 3.5+ MB

In [11]:
#Exportamos
yelp_restaurants.to_pickle('restaurants_yelp_final.pkl')

Ahora reemplazamos en las reviews los ids que hay que reemplazar.